import { AppError } from '../utils/errors.js';
import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, ButtonInteraction } from 'discord.js';
import { getOrCreateUser, adjustBalance } from './userService.js';
import type { TransactionType, GuildConfig } from '@prisma/client';
import { isCooldownActive, getCooldownRemaining, setCooldown } from './cooldownManager.js';
import { formatCurrency } from '../utils/format.js';
import { reactToGameResult, type GameResultKey } from '../utils/gameReactions.js';

const BLACKJACK_COOLDOWN_MS = 3_000;
const activeGames = new Map<string, BlackjackGame>();
export type BlackjackAction = 'hit' | 'stand' | 'double';
export interface BlackjackGame { sessionId: string; userId: string; dbUserId: string; guildId: string; config: GuildConfig; betAmount: bigint; doubled: boolean; deck: string[]; playerCards: string[]; dealerCards: string[]; status: 'playing' | 'finished'; createdAt: Date; lastUpdatedAt: Date; }
export interface BlackjackResult { userId: string; outcome: 'win' | 'lose' | 'push' | 'blackjack'; playerValue: number; dealerValue: number; playerCards: string[]; dealerCards: string[]; betAmount: bigint; netAmount: bigint; tax: bigint; message: string; newWallet: bigint; }
const suits = ['♠', '♥', '♦', '♣'];
const ranks = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'];
function buildDeck() { const deck: string[] = []; for (const suit of suits) for (const rank of ranks) deck.push(`${rank}${suit}`); return deck; }
function shuffle(deck: string[]) { for (let i = deck.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [deck[i], deck[j]] = [deck[j], deck[i]]; } }
function drawCard(deck: string[]) { return deck.pop() as string; }
function getCardValue(card: string): number { const rank = card.slice(0, -1); if (rank === 'A') return 1; if (['J', 'Q', 'K'].includes(rank)) return 10; return Number(rank); }
function evaluateHand(cards: string[]) { let total = 0; let aces = 0; for (const card of cards) { total += getCardValue(card); if (card.startsWith('A')) aces += 1; } let best = total; for (let i = 0; i < aces; i++) { const candidate = total + 10 * (i + 1); if (candidate <= 21) best = candidate; } return { value: best, isSoft: best !== total }; }
function createSessionId() { return crypto.randomUUID(); }
function formatHand(cards: string[], hideFirst = false): string { if (hideFirst) return `🂠 ${cards.slice(1).join(' ')}`; return cards.join(' '); }
function createActionRow(sessionId: string, canDouble: boolean, disabled = false) { return new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`blackjack:${sessionId}:hit`).setLabel('Hit').setStyle(ButtonStyle.Primary).setDisabled(disabled), new ButtonBuilder().setCustomId(`blackjack:${sessionId}:stand`).setLabel('Stand').setStyle(ButtonStyle.Success).setDisabled(disabled), new ButtonBuilder().setCustomId(`blackjack:${sessionId}:double`).setLabel('Double').setStyle(ButtonStyle.Secondary).setDisabled(disabled || !canDouble)); }
function dealerPlays(state: BlackjackGame) { while (true) { const { value, isSoft } = evaluateHand(state.dealerCards); if (value >= 17 && (!isSoft || value > 17)) break; state.dealerCards.push(drawCard(state.deck)); } }
function getOutcome(state: BlackjackGame): 'win' | 'lose' | 'push' | 'blackjack' { const playerValue = evaluateHand(state.playerCards).value; const dealerValue = evaluateHand(state.dealerCards).value; const playerBlackjack = state.playerCards.length === 2 && playerValue === 21; const dealerBlackjack = state.dealerCards.length === 2 && dealerValue === 21; if (playerValue > 21) return 'lose'; if (playerBlackjack && !dealerBlackjack) return 'blackjack'; if (dealerBlackjack) return 'lose'; if (dealerValue > 21 || playerValue > dealerValue) return 'win'; if (playerValue < dealerValue) return 'lose'; return 'push'; }

export async function createBlackjackGame(userId: string, guildId: string, betAmount: bigint) {
  const existing = [...activeGames.values()].find(game => game.userId === userId && game.guildId === guildId && game.status === 'playing');
  if (existing) return { game: existing, config: existing.config, resumed: true };
  if (isCooldownActive(userId, 'blackjack')) throw new AppError(`Blackjack is still on cooldown. Try again in ${formatDuration(getCooldownRemaining(userId, 'blackjack'))}.`);
  const { user, config } = await getOrCreateUser(userId, guildId);
  if (betAmount <= 0n) throw new AppError('Bet amount must be greater than zero.');
  if (user.wallet < betAmount) throw new AppError('You do not have enough wallet balance for that bet.');
  await adjustBalance(user.id, { walletDelta: -betAmount }, { source: 'blackjack', amount: -betAmount, type: 'BALANCE' as TransactionType, description: 'Blackjack entry bet' });
  const deck = buildDeck(); shuffle(deck); const game: BlackjackGame = { sessionId: createSessionId(), userId, dbUserId: user.id, guildId, config, betAmount, doubled: false, deck, playerCards: [drawCard(deck), drawCard(deck)], dealerCards: [drawCard(deck), drawCard(deck)], status: 'playing', createdAt: new Date(), lastUpdatedAt: new Date() };
  activeGames.set(game.sessionId, game); setCooldown(userId, 'blackjack', BLACKJACK_COOLDOWN_MS); return { game, config, resumed: false };
}
function getGame(sessionId: string) { const game = activeGames.get(sessionId); if (!game) throw new AppError('This blackjack session no longer exists or has expired.'); return game; }
async function finalizeGame(game: BlackjackGame) { dealerPlays(game); game.status = 'finished'; game.lastUpdatedAt = new Date(); activeGames.delete(game.sessionId); const playerValue = evaluateHand(game.playerCards).value; const dealerValue = evaluateHand(game.dealerCards).value; const result = getOutcome(game); let grossReturn = 0n; let netAmount = -game.betAmount; let message = ''; if (result === 'lose') message = `❌ You lost ${formatCurrency(game.betAmount, game.config.currencyEmoji)}.`; else if (result === 'push') { grossReturn = game.betAmount; netAmount = 0n; message = `🤝 Push! Your bet is returned.`; } else { grossReturn = result === 'blackjack' ? (game.betAmount * 150n) / 100n : game.betAmount * 2n; netAmount = grossReturn - game.betAmount; message = result === 'blackjack' ? `🃏 Blackjack! You won ${formatCurrency(netAmount, game.config.currencyEmoji)}.` : `🎉 You won ${formatCurrency(netAmount, game.config.currencyEmoji)}.`; } const updatedUser = grossReturn > 0n ? await adjustBalance(game.dbUserId, { walletDelta: grossReturn }, { source: 'blackjack', amount: grossReturn, type: 'BALANCE' as TransactionType, description: `Blackjack ${result} return` }) : await getOrCreateUser(game.userId, game.guildId).then(value => value.user); return { userId: game.userId, outcome: result, playerValue, dealerValue, playerCards: game.playerCards, dealerCards: game.dealerCards, betAmount: game.betAmount, netAmount, tax: 0n, message, newWallet: updatedUser.wallet }; }
export async function handleBlackjackAction(sessionId: string, action: BlackjackAction, userId: string) { const game = getGame(sessionId); if (game.userId !== userId) throw new AppError('Only the player who started this game can control it.'); if (game.status !== 'playing') throw new AppError('This blackjack session has already finished.'); if (action === 'double') { if (game.doubled) throw new AppError('You may only double once.'); if (game.playerCards.length !== 2) throw new AppError('You can only double on your first move.'); const user = await getOrCreateUser(game.userId, game.guildId); if (user.user.wallet < game.betAmount) throw new AppError('You do not have enough wallet balance to double.'); await adjustBalance(game.dbUserId, { walletDelta: -game.betAmount }, { source: 'blackjack', amount: -game.betAmount, type: 'BALANCE' as TransactionType, description: 'Blackjack double bet' }); game.betAmount *= 2n; game.doubled = true; game.playerCards.push(drawCard(game.deck)); return finalizeGame(game); } if (action === 'hit') { game.playerCards.push(drawCard(game.deck)); game.lastUpdatedAt = new Date(); if (evaluateHand(game.playerCards).value > 21) return finalizeGame(game); return null; } if (action === 'stand') return finalizeGame(game); throw new AppError('Unknown blackjack action.'); }
export function buildBlackjackEmbed(game: BlackjackGame, config: { currencyEmoji: string }) { const playerValue = evaluateHand(game.playerCards).value; return new EmbedBuilder().setTitle('🃏 WIMPLY BLACKJACK').setDescription(`💰 Bet: **${formatCurrency(game.betAmount, config.currencyEmoji)}**${game.doubled ? ' • Doubled' : ''}\n🎮 Session: **${game.sessionId.slice(0, 6)}**`).addFields({ name: 'Your Hand', value: `${formatHand(game.playerCards)} (${playerValue})`, inline: false }, { name: 'Dealer Hand', value: formatHand(game.dealerCards, true), inline: false }).setFooter({ text: 'Your unfinished hand is resumed automatically when blackjack is started again.' }); }
export function buildResultEmbed(result: BlackjackResult, config: { currencyEmoji: string }) { return new EmbedBuilder().setTitle(result.outcome === 'lose' ? 'Blackjack Loss' : result.outcome === 'push' ? 'Push' : 'Blackjack Win').setDescription(result.message).addFields({ name: 'Your Hand', value: `${formatHand(result.playerCards)} (${result.playerValue})`, inline: false }, { name: 'Dealer Hand', value: `${formatHand(result.dealerCards)} (${result.dealerValue})`, inline: false }, { name: 'Wallet Change', value: formatCurrency(result.netAmount, config.currencyEmoji), inline: true }, { name: 'New Wallet', value: formatCurrency(result.newWallet, config.currencyEmoji), inline: true }); }
export async function handleBlackjackButtonInteraction(interaction: ButtonInteraction) { const [prefix, sessionId, action] = interaction.customId.split(':'); if (prefix !== 'blackjack' || !sessionId || !action) throw new AppError('Invalid blackjack button interaction.'); if (!['hit', 'stand', 'double'].includes(action)) throw new AppError('Invalid blackjack action.'); const gameBeforeAction = activeGames.get(sessionId); const currencyEmoji = gameBeforeAction?.config.currencyEmoji ?? '🪙'; const result = await handleBlackjackAction(sessionId, action as BlackjackAction, interaction.user.id); if (!result) { const game = activeGames.get(sessionId); if (!game) throw new AppError('Blackjack session expired.'); await interaction.update({ embeds: [buildBlackjackEmbed(game, { currencyEmoji: game.config.currencyEmoji })], components: [createActionRow(sessionId, !game.doubled, false)] }); return null; } await interaction.update({ embeds: [buildResultEmbed(result, { currencyEmoji })], components: [createActionRow(sessionId, false, true)] }); const reactionKey: GameResultKey = result.outcome === 'blackjack' ? 'BLACKJACK_BLACKJACK' : result.outcome === 'win' ? 'BLACKJACK_WIN' : result.outcome === 'push' ? 'BLACKJACK_PUSH' : 'BLACKJACK_LOSS'; const resultMessage = await interaction.fetchReply().catch(() => null); await reactToGameResult(resultMessage, reactionKey); return result; }
export { createActionRow, activeGames };
function formatDuration(ms: number) { const seconds = Math.ceil(ms / 1000); const minutes = Math.floor(seconds / 60); const hours = Math.floor(minutes / 60); const remainingSeconds = seconds % 60; const remainingMinutes = minutes % 60; if (hours) return `${hours}h ${remainingMinutes}m ${remainingSeconds}s`; if (minutes) return `${remainingMinutes}m ${remainingSeconds}s`; return `${seconds}s`; }
