import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, Colors } from 'discord.js';
import type { ButtonInteraction, Interaction } from 'discord.js';
import { log } from '../utils/logger.js';
import { handleInteractionError } from '../utils/errorHandler.js';
import { handleBlackjackButtonInteraction } from '../services/blackjackService.js';
import { higherLowerGames, minesGames, minesMultiplier, payGame, cleanupExpiredGames } from '../services/miniGameService.js';
import { aviatorGames, cashOutAviator, getAviatorMultiplier } from '../services/aviatorService.js';
import { reactToMatchingMessage } from '../services/reactionService.js';
import { formatCurrency } from '../utils/format.js';
import { polishPayload } from '../utils/presentation.js';
function gameEmbed(title: string, description: string) { return new EmbedBuilder().setColor(Colors.Blurple).setTitle(title).setDescription(description).setTimestamp(); }
function warningEmbed(title: string, description: string) { return gameEmbed(title, description); }
function wompy(interaction: ButtonInteraction) { return interaction.guild?.emojis.cache.find(e => e.name === 'Wompy')?.toString() ?? 'Wompy'; }
function minesRows(id: string, revealed: Set<number>, mines?: Set<number>) { return Array.from({ length: 5 }, (_, r) => { const row = new ActionRowBuilder<ButtonBuilder>(); for (let c = 0; c < 5; c++) { const index = r * 5 + c; const isMine = mines?.has(index); const isRevealed = revealed.has(index); row.addComponents(new ButtonBuilder().setCustomId(`mines:cell:${id}:${index}`).setLabel(isRevealed ? (isMine ? '💣' : '💎') : '▫️').setStyle(isRevealed ? ButtonStyle.Secondary : ButtonStyle.Primary).setDisabled(Boolean(isRevealed))); } return row; }); }
function minesCashoutRow(id: string, enabled: boolean) { return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`mines:cashout:${id}`).setLabel('💰 Cash Out').setStyle(ButtonStyle.Success).setDisabled(!enabled))]; }
function withPolishedResponses<T extends Interaction>(interaction: T): T { const clientUser = interaction.client.user; return new Proxy(interaction, { get(target, property, receiver) { if (property === 'reply' || property === 'editReply' || property === 'followUp' || property === 'update') return (payload: unknown) => (target as any)[property](polishPayload(payload as any, clientUser)); return Reflect.get(target, property, receiver); } }); }
async function handleMiniGameButton(interaction: ButtonInteraction) {
  cleanupExpiredGames(); const parts = interaction.customId.split(':');
  if (parts[0] === 'aviator') { const action = parts[1]; const id = parts.slice(2).join(':'); const game = aviatorGames.get(id); if (!game || game.discordId !== interaction.user.id) { await interaction.reply({ embeds: [warningEmbed('⏳ AVIATOR EXPIRED', 'This flight is no longer active.')], ephemeral: true }); return true; } if (action === 'cashout') { game.multiplier = getAviatorMultiplier(game); try { const result = await cashOutAviator(id, interaction.user.id, game.multiplier); const currency = wompy(interaction); await interaction.update({ embeds: [gameEmbed('💰 AVIATOR • CASHED OUT', `✈️ **Flight secured.**\n\n📈 Multiplier: **${result.multiplier.toFixed(2)}×**\n💰 Wager: **${formatCurrency(result.session.bet, currency)}**\n🏆 Payout: **${formatCurrency(result.payout, currency)}**\n💎 Profit: **${formatCurrency(result.payout - result.session.bet, currency)}**`)], components: [] }); } catch (error) { await interaction.reply({ embeds: [warningEmbed('⚠️ CASH OUT FAILED', error instanceof Error ? error.message : String(error))], ephemeral: true }); } return true; } }
  if (parts[0] === 'hl') { const action = parts[1]; const id = parts.slice(2).join(':'); const game = higherLowerGames.get(id); if (!game || game.userId !== interaction.user.id) { await interaction.reply({ embeds: [warningEmbed('⏳ GAME EXPIRED', 'This Higher/Lower session is no longer active.')], ephemeral: true }); return true; } const currency = wompy(interaction); if (action === 'cashout') { if (game.moves < 1) { await interaction.reply({ embeds: [warningEmbed('⚠️ CASH OUT BLOCKED', 'Make at least **1 prediction** before cashing out.')], ephemeral: true }); return true; } const payout = game.bet * BigInt(Math.round(game.multiplier * 100)) / 100n; await payGame(game.userId, game.guildId, payout, 'Higher/Lower'); higherLowerGames.delete(id); await interaction.update({ embeds: [gameEmbed('💰 HIGHER / LOWER • CASHED OUT', `You secured **${formatCurrency(payout, currency)}**.\n\n🎯 Predictions: **${game.moves}**\n📈 Multiplier: **${game.multiplier.toFixed(2)}×**`)], components: [] }); return true; } const next = Math.floor(Math.random() * 100) + 1; const correct = action === 'higher' ? next > game.current : next < game.current; game.moves += 1; if (!correct) { higherLowerGames.delete(id); await interaction.update({ embeds: [gameEmbed('💥 HIGHER / LOWER • LOST', `**Miss!** 🎯\n\nPrevious: **${game.current}**\nNext: **${next}**\nPredictions: **${game.moves}**\nBet lost: **${formatCurrency(game.bet, currency)}**`)], components: [] }); return true; } game.current = next; game.multiplier = Math.min(8, game.multiplier + 0.5); game.expiresAt = Date.now() + 5 * 60_000; const potential = game.bet * BigInt(Math.round(game.multiplier * 100)) / 100n; await interaction.update({ embeds: [gameEmbed('🎯 HIGHER / LOWER', `**Correct!** 🎯\n\nNew number: **${game.current}**\nPredictions: **${game.moves}**\nMultiplier: **${game.multiplier.toFixed(2)}×**\nCash-out value: **${formatCurrency(potential, currency)}**`)], components: [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`hl:higher:${id}`).setLabel('Higher ⬆️').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId(`hl:lower:${id}`).setLabel('Lower ⬇️').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`hl:cashout:${id}`).setLabel('Cash Out 💰').setStyle(ButtonStyle.Success))] }); return true; }
  if (parts[0] === 'mines') { const action = parts[1]; const id = action === 'cell' ? parts.slice(2, -1).join(':') : parts.slice(2).join(':'); const game = minesGames.get(id); if (!game || game.userId !== interaction.user.id) { await interaction.reply({ embeds: [warningEmbed('⏳ GAME EXPIRED', 'This Mines session is no longer active.')], ephemeral: true }); return true; } const currency = wompy(interaction); if (action === 'cashout') { if (game.revealed.size < 1) { await interaction.reply({ embeds: [warningEmbed('⚠️ CASH OUT BLOCKED', 'Reveal at least **1 safe tile** before cashing out.')], ephemeral: true }); return true; } const payout = game.bet * BigInt(Math.round(game.multiplier * 100)) / 100n; const settledBoard = new Set<number>(Array.from({ length: 25 }, (_, i) => i)); await payGame(game.userId, game.guildId, payout, 'Mines'); minesGames.delete(id); await interaction.update({ embeds: [gameEmbed('💰 MINES • CASHED OUT', `You secured **${formatCurrency(payout, currency)}** 💎\n\n💣 Mines: **${game.mineCount}/25**\n💎 Gems found: **${game.revealed.size}**\n📈 Multiplier: **${game.multiplier.toFixed(2)}×**\n\nBoard settled • Session secured`)], components: minesRows(id, settledBoard, game.mines).concat(minesCashoutRow(id, false)) }); return true; } const index = Number(parts.at(-1)); if (!Number.isInteger(index) || index < 0 || index >= 25 || game.revealed.has(index)) return true; game.revealed.add(index); if (game.mines.has(index)) { const settledBoard = new Set<number>(Array.from({ length: 25 }, (_, i) => i)); minesGames.delete(id); await interaction.update({ embeds: [gameEmbed('💣 MINES • HIT', `**BOOM!** 💥\n\n💣 Mines: **${game.mineCount}/25**\n💎 Gems found: **${game.revealed.size - 1}**\n💰 Bet lost: **${formatCurrency(game.bet, currency)}**\n\nBoard settled • Session ended`)], components: minesRows(id, settledBoard, game.mines).concat(minesCashoutRow(id, false)) }); return true; } game.multiplier = minesMultiplier(game.mineCount, game.revealed.size); game.expiresAt = Date.now() + 10 * 60_000; const potential = game.bet * BigInt(Math.round(game.multiplier * 100)) / 100n; const nextMultiplier = game.revealed.size < 25 - game.mineCount ? minesMultiplier(game.mineCount, game.revealed.size + 1) : game.multiplier; await interaction.update({ embeds: [gameEmbed('💎 MINES • SAFE', `**Safe tile!** 💎\n\n💎 Gems found: **${game.revealed.size}**\n💣 Mines: **${game.mineCount}/25**\n📈 Current multiplier: **${game.multiplier.toFixed(2)}×**\n💰 Cash-out value: **${formatCurrency(potential, currency)}**\n📈 Next multiplier: **${nextMultiplier.toFixed(2)}×**\n\n${25 - game.mineCount - game.revealed.size} safe tiles remain`)], components: minesRows(id, game.revealed, game.mines).concat(minesCashoutRow(id, true)) }); return true; }
  if (parts[0] === 'bot' && parts[1] === 'admin') { if (!interaction.memberPermissions?.has('Administrator')) { await interaction.reply({ embeds: [warningEmbed('🔒 ACCESS DENIED', 'You don’t have permission to open the private server snapshot.')], ephemeral: true }); return true; } const bot = interaction.client.user; const app = interaction.client.application; const memory = process.memoryUsage(); await interaction.reply({ content: `🔐 **WIMPLY PRIVATE SNAPSHOT**\nApplication ID: \`${app?.id ?? bot.id}\`\nBot ID: \`${bot.id}\`\nNode: ${process.version}\nMemory RSS: ${(memory.rss / 1024 / 1024).toFixed(1)} MB\nServers: ${interaction.client.guilds.cache.size}\nRuntime: Online`, ephemeral: true }); return true; }
  return false;
}
export default { name: 'interactionCreate', once: false, async execute(interaction: Interaction) { try { if (interaction.isButton()) { if (await handleMiniGameButton(withPolishedResponses(interaction))) return; await handleBlackjackButtonInteraction(withPolishedResponses(interaction) as ButtonInteraction); return; } if (interaction.isChatInputCommand()) { const command = interaction.client.commands?.get(interaction.commandName); if (!command) { log.warn(`Command not found: ${interaction.commandName}`, 'Interaction'); return; } await command.execute(withPolishedResponses(interaction) as any); if (interaction.guildId && (interaction.replied || interaction.deferred)) { try { const response = await interaction.fetchReply(); const resultText = response.embeds.map(embed => `${embed.title ?? ''} ${embed.description ?? ''}`).join(' '); await reactToMatchingMessage(response, interaction.guildId, interaction.channelId, `/${interaction.commandName} ${resultText}`); } catch (error) { log.warn(`Unable to apply response reactions for /${interaction.commandName}: ${error instanceof Error ? error.message : String(error)}`, 'Reaction'); } } } } catch (error) { await handleInteractionError(interaction as Parameters<typeof handleInteractionError>[0], error); } } };
