import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChatInputCommandInteraction, EmbedBuilder, SlashCommandBuilder } from 'discord.js';
import type { Command } from '../../types/command.js';
import { startChicken } from '../../services/chickenCrossRoadService.js';
import { formatCurrency } from '../../utils/format.js';
import { playGameSlides } from '../../utils/gameAnimation.js';

function row(id: string, cashout = false) { return [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`chicken:cross:${id}`).setLabel('🐔 Cross Road').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId(`chicken:cashout:${id}`).setLabel('💰 Cash Out').setStyle(ButtonStyle.Success).setDisabled(!cashout))]; }
function embed(game: { road: number; multiplier: number; bet: bigint }, currency: string, result?: string) { return new EmbedBuilder().setColor(0x5865f2).setTitle('🐔 CHICKEN CROSS ROAD').setDescription(result ?? `## 🐔 Road ${game.road}/10\n\n📈 Multiplier: **${game.multiplier.toFixed(2)}×**\n💰 Wager: **${formatCurrency(game.bet, currency)}**\n🏆 Cash-out value: **${formatCurrency(game.bet * BigInt(Math.round(game.multiplier * 100)) / 100n, currency)}**\n\nChoose **Cross Road** to move forward. Each successful crossing increases the multiplier. Cash Out is available after your first crossing.`).setTimestamp().setFooter({ text: 'Wimply • Created & developed by ẞ€ÑZ¥' }); }
const command: Command = { data: new SlashCommandBuilder().setName('chickencrossroad').setDescription('Cross the road with the chicken and build your multiplier').addStringOption(o => o.setName('amount').setDescription('Amount to wager').setRequired(true)), async execute(interaction: ChatInputCommandInteraction) { if (!interaction.guildId) return; const game = await startChicken(interaction.user.id, interaction.guildId, interaction.options.getString('amount', true)); const currency = interaction.guild?.emojis.cache.find(e => e.name === 'Wompy')?.toString() ?? 'Wompy'; await interaction.deferReply(); const slide = (title: string, description: string, controls = false) => ({ embeds: [embed(game, currency).setTitle(title).setDescription(description)], components: controls ? row(game.id, game.road > 0) : [] }); await playGameSlides([
  { content: slide('🐔 CHICKEN • STARTING', `💰 Wager: **${formatCurrency(game.bet, currency)}**\n\n🛣️ Scanning road…\n🚗 Traffic detected…`), delay: 260 },
  { content: slide('🐔 CHICKEN • ROAD 1', `🐔 The chicken steps to the line.\n\n🛣️ **Road 0/10**\n📈 Multiplier: **1.00×**\n\n⚠️ Traffic is approaching.`), delay: 320 },
  { content: slide('🐔 CHICKEN CROSS ROAD', `## 🐔 Road ${game.road}/10\n\n📈 Multiplier: **${game.multiplier.toFixed(2)}×**\n💰 Wager: **${formatCurrency(game.bet, currency)}**\n🏆 Cash-out value: **${formatCurrency(game.bet, currency)}**\n\nChoose **Cross Road** to move forward. Each successful crossing increases the multiplier.` , true), delay: 0 }
], async (payload) => { await interaction.editReply(payload); }); } };
export default command;
